version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
      
    steps:
      - checkout
      # - restore_cache:
          # keys:
            # - dotnet-packages-v1-{{ checksum "CircleCiCore.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CircleCiCore.csproj" }}

      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
          
      - run:
          name: "Test the executable"
          command: .\CircleCiCore\bin\Release\netcoreapp3.0\publish\CircleCiCore.exe
          
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
      - store_artifacts:
          path: .\CircleCiCore\bin\Release\netcoreapp3.0\publish\CircleCiCore.exe